# Generated by Django 5.2.9 on 2025-12-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_backupconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupconfiguration',
            name='preferred_time',
            field=models.TimeField(default='00:00', help_text='What time should the backup run?'),
        ),
    ]
