# Generated by Django 5.2.9 on 2025-12-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_backupconfiguration_preferred_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupconfiguration',
            name='storage_path',
            field=models.CharField(blank=True, help_text='Custom path for backups (e.g., E:\\Backups). Leave empty for default.', max_length=500, null=True),
        ),
    ]
