# Generated by Django 5.2.9 on 2025-12-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_backupconfiguration_storage_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='absolute_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
