# Generated by Django 5.2.9 on 2025-12-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership_number',
            field=models.CharField(blank=True, help_text='Auto-generated unique ID', max_length=20, null=True),
        ),
    ]
