# Generated by Django 5.2.9 on 2025-12-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_member_membership_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_number',
            field=models.CharField(blank=True, help_text='Auto-generated unique ID', max_length=20, unique=True),
        ),
    ]
