# Generated by Django 5.2.6 on 2025-12-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_dependent_church_member_church_membertransfer_church_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='current_position',
        ),
        migrations.AddField(
            model_name='member',
            name='current_positions',
            field=models.ManyToManyField(blank=True, related_name='members', to='membership.position'),
        ),
    ]
