# Generated by Django 5.2.9 on 2025-12-15 09:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='expense_type',
            field=models.CharField(choices=[('opex', 'Operational Expenditure (OPEX)'), ('capex', 'Capital Expenditure (CAPEX)')], default='opex', max_length=10),
        ),
        migrations.CreateModel(
            name='BudgetExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('feb', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mar', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('apr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('may', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('jun', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('jul', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aug', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sep', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('oct', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nov', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dec', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_items', to='finance.annualbudget')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.expensecategory')),
            ],
            options={
                'unique_together': {('budget', 'category')},
            },
        ),
        migrations.CreateModel(
            name='BudgetIncomeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('feb', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mar', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('apr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('may', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('jun', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('jul', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aug', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sep', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('oct', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nov', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dec', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_items', to='finance.annualbudget')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.incomecategory')),
            ],
            options={
                'unique_together': {('budget', 'category')},
            },
        ),
    ]
