# Generated by Django 5.2.9 on 2025-12-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_assetcategory_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_code',
            field=models.CharField(blank=True, help_text='Unique Identifier e.g. AST-0001', max_length=50, unique=True),
        ),
    ]
