# Generated by Django 5.2.9 on 2025-12-18 19:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('finance', '0004_alter_asset_asset_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budgetexpenseitem',
            unique_together={('budget', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='budgetincomeitem',
            unique_together={('budget', 'category')},
        ),
        migrations.AddField(
            model_name='annualbudget',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
        migrations.AddField(
            model_name='asset',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
        migrations.AddField(
            model_name='budgetexpenseitem',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
        migrations.AddField(
            model_name='budgetincomeitem',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
        migrations.AddField(
            model_name='expense',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
        migrations.AddField(
            model_name='income',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
        migrations.AddField(
            model_name='remittance',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
        migrations.AddField(
            model_name='remittancesettings',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
        migrations.AlterField(
            model_name='annualbudget',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_code',
            field=models.CharField(blank=True, help_text='Unique Identifier e.g. AST-0001', max_length=50),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='incomecategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='remittancesettings',
            name='remittance_type',
            field=models.CharField(choices=[('synod', 'Synod'), ('synod_hc', 'Synod Holy Communion'), ('presbytery', 'Presbytery'), ('consistory', 'Consistory')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='annualbudget',
            unique_together={('church', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('church', 'asset_code')},
        ),
        migrations.AlterUniqueTogether(
            name='assetcategory',
            unique_together={('church', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='budgetexpenseitem',
            unique_together={('budget', 'category'), ('church', 'budget', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='budgetincomeitem',
            unique_together={('budget', 'category'), ('church', 'budget', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('church', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='incomecategory',
            unique_together={('church', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='remittancesettings',
            unique_together={('church', 'remittance_type')},
        ),
    ]
