# Generated by Django 5.2.6 on 2026-01-03 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_department'),
        ('core', '0006_backup_absolute_path'),
        ('finance', '0005_alter_budgetexpenseitem_unique_together_and_more'),
        ('groups', '0003_alter_groupleadership_unique_together_and_more'),
        ('membership', '0005_remove_member_current_position_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['category_type', 'name'], 'verbose_name_plural': 'Expense Categories'},
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='annualbudget',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualbudget',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annualbudget',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Lock budget lines from further editing'),
        ),
        migrations.AddField(
            model_name='annualbudget',
            name='notes',
            field=models.TextField(blank=True, help_text='Explanations/Notes for this financial year'),
        ),
        migrations.AddField(
            model_name='budgetexpenseitem',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_expense_items', to='administration.department'),
        ),
        migrations.AddField(
            model_name='budgetexpenseitem',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_expense_items', to='groups.group'),
        ),
        migrations.AddField(
            model_name='budgetexpenseitem',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='budgetexpenseitem',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_expense_items', to='membership.section'),
        ),
        migrations.AddField(
            model_name='budgetincomeitem',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_income_items', to='administration.department'),
        ),
        migrations.AddField(
            model_name='budgetincomeitem',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_income_items', to='groups.group'),
        ),
        migrations.AddField(
            model_name='budgetincomeitem',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='budgetincomeitem',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_income_items', to='membership.section'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='category_type',
            field=models.CharField(choices=[('pe', 'Personal Emoluments (Staff)'), ('admin', 'Administrative Expenses'), ('dept', 'Departmental Budgets'), ('group', 'Groups and Sections'), ('court', 'Higher Court Obligations'), ('other', 'Other Operating Expenses')], default='admin', max_length=10),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='finance.expensecategory'),
        ),
        migrations.AlterField(
            model_name='annualbudget',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft (Open for Edits)'), ('review', 'Under Review'), ('locked', 'Locked (Approved)'), ('closed', 'Closed (Financial Year Ended)')], default='draft', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('church', 'name', 'parent')},
        ),
        migrations.CreateModel(
            name='BudgetAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('budget', 'Overall Budget')], max_length=10)),
                ('item_id', models.IntegerField(blank=True, help_text='ID of the BudgetIncomeItem or BudgetExpenseItem', null=True)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('lock', 'Locked'), ('unlock', 'Unlocked')], max_length=10)),
                ('changes', models.JSONField(help_text='JSON representation of what changed')),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='finance.annualbudget')),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
