# Generated by Django 5.2.9 on 2025-12-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='allowances',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='deductions',
        ),
        migrations.AddField(
            model_name='employee',
            name='education_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='housing_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='medical_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='other_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='education_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='gross_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='housing_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='medical_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='net_pay_calculated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='nhima_deduction',
            field=models.DecimalField(decimal_places=2, default=0, help_text='NHIMA (1%)', max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='other_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='other_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='overtime_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='paye_tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='PAYE Tax', max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='pension_deduction',
            field=models.DecimalField(decimal_places=2, default=0, help_text='NAPSA (5%)', max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
