# Generated by Django 5.2.9 on 2025-12-18 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('hr', '0004_paygrade_employee_leave_days_accrued_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payrollperiod',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together={('payroll_period', 'employee')},
        ),
        migrations.AddField(
            model_name='employee',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
        migrations.AddField(
            model_name='paygrade',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='paygrade',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('church', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='paygrade',
            unique_together={('church', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='payrollperiod',
            unique_together={('church', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together={('church', 'payroll_period', 'employee'), ('payroll_period', 'employee')},
        ),
    ]
