# Generated by Django 5.0.1 on 2025-12-12 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('committee_type', models.CharField(choices=[('STEWARDSHIP', 'Stewardship'), ('DWEC', 'Doctrine Worship and Evangelism'), ('CPDPC', 'Church Projects, Development and Planning'), ('FUNDRAISING', 'Fundraising'), ('MG', 'Marriage and Guidance'), ('CDSJ', 'Community Development and Social Justice'), ('CT', 'Communications and Literature'), ('FUNERALS', 'Funerals'), ('CTC', 'Church Training'), ('LAY_PREACHERS', 'Lay Preachers'), ('CRR', 'Church Rules and Regulations'), ('CATERING', 'Catering')], max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('meeting_schedule', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeLeadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('convenor', 'Convenor'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership', to='committees.committee')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_leadership_roles', to='membership.member')),
            ],
            options={
                'ordering': ['committee', 'role'],
                'unique_together': {('committee', 'role', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='CommitteeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateField()),
                ('left_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='committees.committee')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to='membership.member')),
            ],
            options={
                'ordering': ['committee', 'member__last_name'],
                'unique_together': {('committee', 'member')},
            },
        ),
    ]
