# Generated by Django 5.2.9 on 2025-12-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='committee_type',
        ),
        migrations.AlterField(
            model_name='committee',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
