# Generated by Django 5.2.9 on 2025-12-18 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0002_remove_committee_committee_type_alter_committee_name'),
        ('core', '__first__'),
        ('membership', '0003_alter_member_membership_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='committeeleadership',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='committeemembership',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='committee',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
        migrations.AddField(
            model_name='committeeleadership',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
        migrations.AddField(
            model_name='committeemembership',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='committee',
            unique_together={('church', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='committeeleadership',
            unique_together={('church', 'committee', 'role', 'is_active')},
        ),
        migrations.AlterUniqueTogether(
            name='committeemembership',
            unique_together={('church', 'committee', 'member')},
        ),
    ]
