# Generated by Django 5.2.9 on 2025-12-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestitem',
            name='reserve_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='harvestitem',
            name='item_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='harvestitem',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('sold', 'Sold'), ('failed', 'Failed to Sell'), ('donated', 'Donated to the Needy'), ('kept', 'Kept for Church Use'), ('spoiled', 'Spoiled/Lost')], default='received', max_length=20),
        ),
    ]
