# Generated by Django 5.2.9 on 2025-12-18 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('special_events', '0002_harvestitem_reserve_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
        migrations.AddField(
            model_name='harvestitem',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
        migrations.AddField(
            model_name='pledge',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
        migrations.AddField(
            model_name='specialday',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
    ]
