# Generated by Django 5.0.1 on 2025-12-12 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group_type', models.CharField(choices=[('MCF', "Men's Christian Fellowship"), ('YCF', 'Young Christian Fellowship'), ('WCF', "Women's Christian Fellowship"), ('BB', 'Boys Brigade'), ('GB', 'Girls Brigade'), ('SS', 'Sunday School'), ('CHOIR', 'Church Choir'), ('PRAISE', 'Praise Team'), ('INTERCESSORS', 'Intercessors'), ('CATECHUMEN', 'Catechumen')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('meeting_schedule', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupLeadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('convenor', 'Convenor'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership', to='groups.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_leadership_roles', to='membership.member')),
            ],
            options={
                'ordering': ['group', 'role'],
                'unique_together': {('group', 'role', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateField()),
                ('left_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='membership.member')),
            ],
            options={
                'ordering': ['group', 'member__last_name'],
                'unique_together': {('group', 'member')},
            },
        ),
    ]
