# Generated by Django 5.2.9 on 2025-12-18 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('groups', '0002_remove_group_group_type_alter_group_name'),
        ('membership', '0003_alter_member_membership_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupleadership',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='group',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
        migrations.AddField(
            model_name='groupleadership',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('church', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='groupleadership',
            unique_together={('church', 'group', 'role', 'is_active')},
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('church', 'group', 'member')},
        ),
    ]
