# Generated by Django 5.2.9 on 2025-12-15 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SundayReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('preacher', models.CharField(blank=True, max_length=200)),
                ('worship_leader', models.CharField(blank=True, max_length=200)),
                ('attendance_men', models.PositiveIntegerField(default=0)),
                ('attendance_women', models.PositiveIntegerField(default=0)),
                ('attendance_children', models.PositiveIntegerField(default=0)),
                ('attendance_visitors', models.PositiveIntegerField(default=0)),
                ('total_offering', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tithe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('section_on_duty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_sundays', to='membership.section')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SectionFunds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tithe_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('envelopes_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loose_offering_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('thanksgiving_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.section')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_funds', to='planner.sundayreport')),
            ],
            options={
                'unique_together': {('report', 'section')},
            },
        ),
    ]
