# Generated by Django 5.2.9 on 2025-12-15 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_sundayreport_sectionfunds'),
    ]

    operations = [
        migrations.AddField(
            model_name='sundayreport',
            name='total_items_sale',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total from sold items', max_digits=12),
        ),
        migrations.CreateModel(
            name='SundayItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reserve_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('sold', 'Sold'), ('failed', 'Failed to Sell'), ('donated', 'Donated to the Needy'), ('kept', 'Kept for Church Use'), ('pending', 'Pending / In Stock')], default='pending', max_length=20)),
                ('sold_price', models.DecimalField(decimal_places=2, default=0, help_text='Actual amount realized if sold', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planner.sundayreport')),
            ],
        ),
    ]
