# Generated by Django 5.2.9 on 2025-12-18 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('membership', '0004_dependent_church_member_church_membertransfer_church_and_more'),
        ('planner', '0003_sundayreport_total_items_sale_sundayitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sectionfunds',
            unique_together={('report', 'section')},
        ),
        migrations.AddField(
            model_name='event',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
        migrations.AddField(
            model_name='sectionfunds',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
        migrations.AddField(
            model_name='sundayitem',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
        migrations.AddField(
            model_name='sundayreport',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church'),
        ),
        migrations.AlterField(
            model_name='sundayreport',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='sectionfunds',
            unique_together={('church', 'report', 'section'), ('report', 'section')},
        ),
        migrations.AlterUniqueTogether(
            name='sundayreport',
            unique_together={('church', 'date')},
        ),
    ]
